// 
// Generated by @himenon/openapi-typescript-code-generator
// 
// OpenApi : 3.0.0
// 
// 


export interface Parameter$getChat {
    message?: string;
}
export interface Response$getChat$Status$200 {
    "text/event-stream": string;
}
export type ResponseContentType$getChat = keyof Response$getChat$Status$200;
export interface Params$getChat {
    parameter: Parameter$getChat;
}
export type HttpMethod = "GET" | "PUT" | "POST" | "DELETE" | "OPTIONS" | "HEAD" | "PATCH" | "TRACE";
export interface ObjectLike {
    [key: string]: any;
}
export interface QueryParameter {
    value: any;
    style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    explode: boolean;
}
export interface QueryParameters {
    [key: string]: QueryParameter;
}
export type SuccessResponses = Response$getChat$Status$200;
export namespace ErrorResponse {
    export type getChat = void;
}
export interface Encoding {
    readonly contentType?: string;
    headers?: Record<string, any>;
    readonly style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    readonly explode?: boolean;
    readonly allowReserved?: boolean;
}
export interface RequestArgs {
    readonly httpMethod: HttpMethod;
    readonly url: string;
    headers: ObjectLike | any;
    requestBody?: ObjectLike | any;
    requestBodyEncoding?: Record<string, Encoding>;
    queryParameters?: QueryParameters | undefined;
}
export interface ApiClient<RequestOption> {
    request: <T = SuccessResponses>(requestArgs: RequestArgs, options?: RequestOption) => Promise<T>;
}
export const createClient = <RequestOption>(apiClient: ApiClient<RequestOption>, baseUrl: string) => {
    const _baseUrl = baseUrl.replace(/\/$/, "");
    return {
        getChat: (params: Params$getChat, option?: RequestOption): Promise<Response$getChat$Status$200["text/event-stream"]> => {
            const url = _baseUrl + `/chat`;
            const headers = {
                Accept: "text/event-stream"
            };
            const queryParameters: QueryParameters = {
                message: { value: params.parameter.message, explode: false }
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers,
                queryParameters: queryParameters
            }, option);
        }
    };
};
type ClientFunction<RequestOption> = typeof createClient<RequestOption>;
export type Client<RequestOption> = ReturnType<ClientFunction<RequestOption>>;
