// eslint-disable-next-line @typescript-eslint/no-var-requires
const pkg = require("../package.json");

export const pattern = `Generated by ${pkg.name} v${pkg.version}`;
export const replacedText = `Generated by ${pkg.name}`;

export const replaceVersionInfo = (text: string): string => {
  return text.replace(pattern, replacedText);
}