// 
// Generated by @himenon/openapi-typescript-code-generator
// 
// OpenApi : 3.1.0
// 
// License  : MIT
// 


export namespace Schemas {
    export type InferArrayEmptyItems = {}[];
    export type InferArrayType = string[];
    export interface InferObjectItem {
        description: any;
    }
    export interface InferObjectHasAnyProp {
        filed?: any;
    }
    export interface InferObject {
        filed?: string;
    }
    export type InferStringEnum = "a" | "b" | "c";
    export type InferAnyNullable = null;
    export interface OptionalPropertiesAndAdditionalProperties {
        body?: {
            key?: string;
            description?: string;
        } & {
            [key: string]: string;
        };
    }
}
