//
// Generated by @himenon/openapi-typescript-code-generator v0.26.1
//
// OpenApi : 3.1.0
//
// License  : MIT
//

export namespace Schemas {
  export interface CustomType {
    name?: string;
  }
  export type BinaryFormat_String = string;
  export type IntOrStringFormat_String = string;
  export type CustomTypeFormat_String = string;
  export type DateTimeFormat_String = string;
  export type BinaryFormat_Int = number;
  export type IntOrStringFormat_Int = number;
  export type CustomTypeFormat_Int = number;
  export type DateTimeFormat_Int = number;
  export interface ObjectPropertyCustomType {
    date?: string;
  }
  export type Binary = string;
  export type IntOrString = string;
  export type AandB = string;
}
