openapi: 3.0.3
info:
  version: 1.0.0
  title: DEMO
  description: demo spec
  license:
    name: MIT

servers:
  - url: "http://dev.api.test.domain/"
    description: Development Environment
  - url: "https://api.test.domain/"
    description: Production Environment

paths:
  /get/books:
    get:
      operationId: getBooks
      responses:
        200:
          $ref: "./components/responses/Books.yml"
  /search/books:
    get:
      operationId: searchBooks
      parameters:
        - in: query
          name: filter
          explode: true
          style: deepObject
          schema:
            type: object
            required:
              - title
              - author
            properties:
              title:
                type: string
                nullable: true
              author:
                type: string
                nullable: true
            additionalProperties:
              type: string
      responses:
        200:
          description: Get Books
          content:
            application/json:
              schema:
                type: object
                properties:
                  books:
                    type: array
                    items:
                      $ref: "./components/schemas/Book.yml"
