// 
// Generated by @himenon/openapi-typescript-code-generator v2.0.4
// 
// OpenApi : 3.0.0
// 
// License  : MIT
// 


export namespace Schemas {
    export interface Foo {
        bar?: {
            baz?: string;
            bazbaz?: {
                hoge?: number;
            };
        };
    }
    export type Bar = {
        baz?: string;
        bazbaz?: {
            hoge?: number;
        };
    };
    export type Baz = string;
    export type Hoge = number;
    export type BazBaz = {
        hoge?: number;
    };
}
