import { EOL } from "os";
import ts from "typescript";
import * as TypeScriptCodeGenerator from "../TypeScriptCodeGenerator";
import { OpenApi } from "../OpenApiParser";
import * as Parameters from "./Parameters";
import * as Schemas from "./Schemas";
import * as Responses from "./Responses";
import * as RequestBodies from "./RequestBodies";
import * as Headers from "./Headers";
import * as SecuritySchemas from "./SecuritySchemas";
import * as PathItems from "./PathItems";

const generateLeadingComment = (schema: OpenApi.OpenApi310): string => {
  const messages: string[] = [];
  messages.push("");
  messages.push("Generated by @himenon/openapi-typescript-ast-codegen v0.1.0");
  messages.push("");
  messages.push(`OpenApi : ${schema.openapi}`);
  messages.push("");
  if (schema.info.license) {
    if (schema.info.license.name) {
      messages.push(`License  : ${schema.info.license.name}`);
    }
    if (schema.info.license.url) {
      messages.push(`Url      : ${schema.info.license.url}`);
    }
  }
  if (schema.info.contact) {
    messages.push(`Contact:`);
    if (schema.info.contact.name) {
      messages.push(`  Name  : ${schema.info.contact.name}`);
    }
    if (schema.info.contact.email) {
      messages.push(`  Email : ${schema.info.contact.email}`);
    }
    if (schema.info.contact.url) {
      messages.push(`  Url   : ${schema.info.contact.url}`);
    }
    messages.push("");
  }
  if (schema.externalDocs) {
    messages.push(`Document:`);
    if (schema.externalDocs.description) {
      messages.push(`  Description : ${schema.externalDocs.description}`);
    }
    if (schema.externalDocs.url) {
      messages.push(`  Url         : ${schema.externalDocs.url}`);
    }
  }
  messages.push("");
  return messages
    .map(message => {
      return `// ${message}`;
    })
    .join(EOL);
};

export interface Converter {
  generateLeadingComment: () => string;
  createFunction: TypeScriptCodeGenerator.CreateFunction;
}

export const create = (entryPoint: string, rootSchema: OpenApi.OpenApi310): Converter => {
  const currentPoint = entryPoint;
  const createFunction = (context: ts.TransformationContext): ts.Statement[] => {
    const statements: ts.Statement[] = [];
    const factory = TypeScriptCodeGenerator.Factory.create(context);
    ts.addSyntheticLeadingComment;
    if (rootSchema.components) {
      if (rootSchema.components.schemas) {
        statements.push(Schemas.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.schemas));
      }
      if (rootSchema.components.headers) {
        statements.push(Headers.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.headers));
      }
      if (rootSchema.components.responses) {
        statements.push(Responses.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.responses));
      }
      if (rootSchema.components.parameters) {
        statements.push(Parameters.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.parameters));
      }
      if (rootSchema.components.requestBodies) {
        statements.push(RequestBodies.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.requestBodies));
      }
      if (rootSchema.components.securitySchemes) {
        statements.push(SecuritySchemas.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.securitySchemes));
      }
      if (rootSchema.components.pathItems) {
        statements.push(PathItems.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.pathItems));
      }
      // TODO
      // if (rootSchema.components.links) {
      //   statements.push(Links.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.links));
      // }

      // TODO
      // if (rootSchema.components.callbacks) {
      //   statements.push(Callbacks.generateNamespace(entryPoint, currentPoint, factory, rootSchema.components.callbacks));
      // }
    }
    return statements;
  };

  return {
    createFunction,
    generateLeadingComment: () => generateLeadingComment(rootSchema),
  };
};
