// 
// Generated by @himenon/openapi-typescript-code-generator v2.0.4
// 
// OpenApi : 3.1.0
// 
// License  : MIT
// 


export namespace Schemas {
    export interface Book {
        author?: {
            name?: string;
            age?: string;
        };
        publisher?: {
            name?: any;
            address?: string;
        };
        metadata: {
            description: string;
        };
    }
    export type Author = {
        name?: string;
        age?: string;
    };
    export type Publisher = {
        name?: any;
        address?: string;
    };
}
export interface Parameter$getBook {
    /** Book ID */
    id: string;
}
export interface Response$getBook$Status$200 {
    "application/json": Schemas.Book;
}
export interface Parameter$getDescription {
    /** Book ID */
    id: string;
}
export interface Response$getDescription$Status$200 {
    "application/json": string;
}
export interface Parameter$getAuthor {
    /** Author Id */
    id: string;
}
export interface Response$getAuthor$Status$200 {
    "application/json": {
        name?: string;
        age?: string;
    };
}
export interface Parameter$getPublisher {
    /** Publisher ID */
    id: string;
}
export interface Response$getPublisher$Status$200 {
    "application/json": Schemas.Publisher;
}
export interface RequestBody$createPublisher {
    "application/x-www-form-urlencoded": {
        color?: string[];
    };
}
export interface Response$createPublisher$Status$200 {
    "application/json": {
        status?: string;
    };
}
export interface RequestBody$createPublisherV2 {
    "application/x-www-form-urlencoded": {
        color?: string[];
    };
    "application/json": {
        color?: string[];
    };
}
export interface Response$createPublisherV2$Status$200 {
    "application/json": {
        status?: string;
    };
}
export interface Parameter$getBookById {
    /** Author ID */
    authorId: string;
    /** Book ID */
    bookId: string;
}
export interface Response$getBookById$Status$200 {
    "application/json": Schemas.Book;
}
export type ResponseContentType$getBook = keyof Response$getBook$Status$200;
export interface Params$getBook {
    parameter: Parameter$getBook;
}
export type ResponseContentType$getDescription = keyof Response$getDescription$Status$200;
export interface Params$getDescription {
    parameter: Parameter$getDescription;
}
export type ResponseContentType$getAuthor = keyof Response$getAuthor$Status$200;
export interface Params$getAuthor {
    parameter: Parameter$getAuthor;
}
export type ResponseContentType$getPublisher = keyof Response$getPublisher$Status$200;
export interface Params$getPublisher {
    parameter: Parameter$getPublisher;
}
export type RequestContentType$createPublisher = keyof RequestBody$createPublisher;
export type ResponseContentType$createPublisher = keyof Response$createPublisher$Status$200;
export interface Params$createPublisher {
    requestBody: RequestBody$createPublisher["application/x-www-form-urlencoded"];
}
export type RequestContentType$createPublisherV2 = keyof RequestBody$createPublisherV2;
export type ResponseContentType$createPublisherV2 = keyof Response$createPublisherV2$Status$200;
export interface Params$createPublisherV2<T extends RequestContentType$createPublisherV2> {
    headers: {
        "Content-Type": T;
    };
    requestBody: RequestBody$createPublisherV2[T];
}
export type ResponseContentType$getBookById = keyof Response$getBookById$Status$200;
export interface Params$getBookById {
    parameter: Parameter$getBookById;
}
export type HttpMethod = "GET" | "PUT" | "POST" | "DELETE" | "OPTIONS" | "HEAD" | "PATCH" | "TRACE";
export interface ObjectLike {
    [key: string]: any;
}
export interface QueryParameter {
    value: any;
    style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    explode: boolean;
}
export interface QueryParameters {
    [key: string]: QueryParameter;
}
export type SuccessResponses = Response$getBook$Status$200 | Response$getDescription$Status$200 | Response$getAuthor$Status$200 | Response$getPublisher$Status$200 | Response$createPublisher$Status$200 | Response$createPublisherV2$Status$200 | Response$getBookById$Status$200;
export namespace ErrorResponse {
    export type getBook = void;
    export type getDescription = void;
    export type getAuthor = void;
    export type getPublisher = void;
    export type createPublisher = void;
    export type createPublisherV2 = void;
    export type getBookById = void;
}
export interface Encoding {
    readonly contentType?: string;
    headers?: Record<string, any>;
    readonly style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    readonly explode?: boolean;
    readonly allowReserved?: boolean;
}
export interface RequestArgs {
    readonly httpMethod: HttpMethod;
    readonly url: string;
    headers: ObjectLike | any;
    requestBody?: ObjectLike | any;
    requestBodyEncoding?: Record<string, Encoding>;
    queryParameters?: QueryParameters | undefined;
}
export interface ApiClient<RequestOption> {
    request: <T = SuccessResponses>(requestArgs: RequestArgs, options?: RequestOption) => Promise<T>;
}
export const createClient = <RequestOption>(apiClient: ApiClient<RequestOption>, baseUrl: string) => {
    const _baseUrl = baseUrl.replace(/\/$/, "");
    return {
        getBook: (params: Params$getBook, option?: RequestOption): Promise<Response$getBook$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/book/${encodeURIComponent(params.parameter.id)}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        getDescription: (params: Params$getDescription, option?: RequestOption): Promise<Response$getDescription$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/book/${encodeURIComponent(params.parameter.id)}/description`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        getAuthor: (params: Params$getAuthor, option?: RequestOption): Promise<Response$getAuthor$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/author/${encodeURIComponent(params.parameter.id)}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        getPublisher: (params: Params$getPublisher, option?: RequestOption): Promise<Response$getPublisher$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/publisher/${encodeURIComponent(params.parameter.id)}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        createPublisher: (params: Params$createPublisher, option?: RequestOption): Promise<Response$createPublisher$Status$200["application/json"]> => {
            const url = _baseUrl + `/create/publisher/{id}`;
            const headers = {
                "Content-Type": "application/x-www-form-urlencoded",
                Accept: "application/json"
            };
            const requestEncodings: Record<string, Record<string, Encoding>> = {
              "application/x-www-form-urlencoded": {
                "color": {
                  "style": "form",
                  "explode": false
                }
              }
            };
            return apiClient.request({
                httpMethod: "POST",
                url,
                headers,
                requestBody: params.requestBody,
                requestBodyEncoding: requestEncodings["application/x-www-form-urlencoded"]
            }, option);
        },
        createPublisherV2: <RequestContentType extends RequestContentType$createPublisherV2>(params: Params$createPublisherV2<RequestContentType>, option?: RequestOption): Promise<Response$createPublisherV2$Status$200["application/json"]> => {
            const url = _baseUrl + `/create/v2/publisher/{id}`;
            const headers = {
                "Content-Type": params.headers["Content-Type"],
                Accept: "application/json"
            };
            const requestEncodings: Record<string, Record<string, Encoding>> = {
              "application/x-www-form-urlencoded": {
                "color": {
                  "style": "form",
                  "explode": false
                }
              },
              "application/json": {
                "color": {
                  "style": "form",
                  "explode": false
                }
              }
            };
            return apiClient.request({
                httpMethod: "POST",
                url,
                headers,
                requestBody: params.requestBody,
                requestBodyEncoding: requestEncodings[params.headers["Content-Type"]]
            }, option);
        },
        getBookById: (params: Params$getBookById, option?: RequestOption): Promise<Response$getBookById$Status$200["application/json"]> => {
            const url = _baseUrl + `/author/author-${encodeURIComponent(params.parameter.authorId)}.a.${encodeURIComponent(params.parameter.bookId)}.b/book/${encodeURIComponent(params.parameter.bookId)}.json`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        }
    };
};
type ClientFunction<RequestOption> = typeof createClient<RequestOption>;
export type Client<RequestOption> = ReturnType<ClientFunction<RequestOption>>;
