// 
// Generated by @himenon/openapi-typescript-code-generator
// 
// OpenApi : 3.1.0
// 
// License  : MIT
// 


export namespace Schemas {
    export interface Book {
        author?: {
            name?: string;
            age?: string;
        };
        publisher?: {
            name?: any;
            address?: string;
        };
        metadata: {
            description: string;
        };
    }
    export namespace Book {
        export namespace properties {
            export interface author {
                name?: string;
                age?: string;
            }
            export interface publisher {
                name?: any;
                address?: string;
            }
            export namespace metadata {
                export namespace properties {
                    export type description = string;
                }
            }
        }
    }
    export type Author = Schemas.Book.properties.author;
    export type Publisher = Schemas.Book.properties.publisher;
}
export interface Parameter$getBook {
    /** Book ID */
    id: string;
}
export interface Response$getBook$Status$200 {
    "application/json": Schemas.Book;
}
export interface Parameter$getDescription {
    /** Book ID */
    id: string;
}
export interface Response$getDescription$Status$200 {
    "application/json": Schemas.Book.properties.metadata.properties.description;
}
export interface Parameter$getAuthor {
    /** Author Id */
    id: string;
}
export interface Response$getAuthor$Status$200 {
    "application/json": Schemas.Author;
}
export interface Parameter$getPublisher {
    /** Publisher ID */
    id: string;
}
export interface Response$getPublisher$Status$200 {
    "application/json": Schemas.Publisher;
}
export type ResponseContentType$getBook = keyof Response$getBook$Status$200;
export interface Params$getBook {
    parameter: Parameter$getBook;
}
export type ResponseContentType$getDescription = keyof Response$getDescription$Status$200;
export interface Params$getDescription {
    parameter: Parameter$getDescription;
}
export type ResponseContentType$getAuthor = keyof Response$getAuthor$Status$200;
export interface Params$getAuthor {
    parameter: Parameter$getAuthor;
}
export type ResponseContentType$getPublisher = keyof Response$getPublisher$Status$200;
export interface Params$getPublisher {
    parameter: Parameter$getPublisher;
}
export type HttpMethod = "GET" | "PUT" | "POST" | "DELETE" | "OPTIONS" | "HEAD" | "PATCH" | "TRACE";
export interface ObjectLike {
    [key: string]: any;
}
export interface QueryParameter {
    value: any;
    style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    explode: boolean;
}
export interface QueryParameters {
    [key: string]: QueryParameter;
}
export type SuccessResponses = Response$getBook$Status$200 | Response$getDescription$Status$200 | Response$getAuthor$Status$200 | Response$getPublisher$Status$200;
export namespace ErrorResponse {
    export type getBook = void;
    export type getDescription = void;
    export type getAuthor = void;
    export type getPublisher = void;
}
export interface Encoding {
    readonly contentType?: string;
    headers?: Record<string, any>;
    readonly style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    readonly explode?: boolean;
    readonly allowReserved?: boolean;
}
export interface RequestArgs {
    readonly httpMethod: HttpMethod;
    readonly url: string;
    headers: ObjectLike | any;
    requestBody?: ObjectLike | any;
    requestBodyEncoding?: Record<string, Encoding>;
    queryParameters?: QueryParameters | undefined;
}
export interface ApiClient<RequestOption> {
    request: <T = SuccessResponses>(requestArgs: RequestArgs, options?: RequestOption) => Promise<T>;
}
export const createClient = <RequestOption>(apiClient: ApiClient<RequestOption>, baseUrl: string) => {
    const _baseUrl = baseUrl.replace(/\/$/, "");
    return {
        getBook: (params: Params$getBook, option?: RequestOption): Promise<Response$getBook$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/book/${encodeURIComponent(params.parameter.id)}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        getDescription: (params: Params$getDescription, option?: RequestOption): Promise<Response$getDescription$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/book/${encodeURIComponent(params.parameter.id)}/description`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        getAuthor: (params: Params$getAuthor, option?: RequestOption): Promise<Response$getAuthor$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/author/${encodeURIComponent(params.parameter.id)}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        },
        getPublisher: (params: Params$getPublisher, option?: RequestOption): Promise<Response$getPublisher$Status$200["application/json"]> => {
            const url = _baseUrl + `/get/publisher/${encodeURIComponent(params.parameter.id)}`;
            const headers = {
                Accept: "application/json"
            };
            return apiClient.request({
                httpMethod: "GET",
                url,
                headers
            }, option);
        }
    };
};
type ClientFunction<RequestOption> = typeof createClient<RequestOption>;
export type Client<RequestOption> = ReturnType<ClientFunction<RequestOption>>;
