// 
// Generated by @himenon/openapi-typescript-code-generator v2.0.4
// 
// OpenApi : 3.1.0
// 
// License  : MIT
// 


export namespace Schemas {
    export type Message = "hello" | "world";
    export type QueryParams = "a" | "b" | "c";
    export interface ReadOnlyParams {
        readonly readonlyPropertyKey?: string;
    }
}
export interface Parameter$getHelloWorld {
    /** query word */
    word: Schemas.QueryParams;
}
export interface Response$getHelloWorld$Status$200 {
    "application/json": {
        message?: Schemas.Message;
    };
}
export interface RequestBody$postHelloWorldReadonly {
}
export interface Response$postHelloWorldReadonly$Status$200 {
    "application/json": {
        message?: Schemas.Message;
    };
}
export interface Response$get$undefined$operation$$id$Status$200 {
    "application/json": {
        /** Undefined operation response */
        message?: string;
    };
}
export type ResponseContentType$getHelloWorld = keyof Response$getHelloWorld$Status$200;
export interface Params$getHelloWorld {
    parameter: Parameter$getHelloWorld;
}
export type RequestContentType$postHelloWorldReadonly = keyof RequestBody$postHelloWorldReadonly;
export type ResponseContentType$postHelloWorldReadonly = keyof Response$postHelloWorldReadonly$Status$200;
export interface Params$postHelloWorldReadonly {
    requestBody: RequestBody$postHelloWorldReadonly["application/json"];
}
export type ResponseContentType$get$undefined$operation$$id = keyof Response$get$undefined$operation$$id$Status$200;
export type HttpMethod = "GET" | "PUT" | "POST" | "DELETE" | "OPTIONS" | "HEAD" | "PATCH" | "TRACE";
export interface ObjectLike {
    [key: string]: any;
}
export interface QueryParameter {
    value: any;
    style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    explode: boolean;
}
export interface QueryParameters {
    [key: string]: QueryParameter;
}
export type SuccessResponses = Response$getHelloWorld$Status$200 | Response$postHelloWorldReadonly$Status$200 | Response$get$undefined$operation$$id$Status$200;
export namespace ErrorResponse {
    export type getHelloWorld = void;
    export type postHelloWorldReadonly = void;
    export type get$undefined$operation$$id = void;
}
export interface Encoding {
    readonly contentType?: string;
    headers?: Record<string, any>;
    readonly style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    readonly explode?: boolean;
    readonly allowReserved?: boolean;
}
export interface RequestArgs {
    readonly httpMethod: HttpMethod;
    readonly url: string;
    headers: ObjectLike | any;
    requestBody?: ObjectLike | any;
    requestBodyEncoding?: Record<string, Encoding>;
    queryParameters?: QueryParameters | undefined;
}
export interface ApiClient<RequestOption> {
    request: <T = SuccessResponses>(requestArgs: RequestArgs, options?: RequestOption) => Promise<T>;
}
export class Client<RequestOption> {
    private baseUrl: string;
    constructor(private apiClient: ApiClient<RequestOption>, baseUrl: string) { this.baseUrl = baseUrl.replace(/\/$/, ""); }
    public async getHelloWorld(params: Params$getHelloWorld, option?: RequestOption): Promise<Response$getHelloWorld$Status$200["application/json"]> {
        const url = this.baseUrl + `/hello/world`;
        const headers = {
            Accept: "application/json"
        };
        const queryParameters: QueryParameters = {
            word: { value: params.parameter.word, explode: false }
        };
        return this.apiClient.request({
            httpMethod: "GET",
            url,
            headers,
            queryParameters: queryParameters
        }, option);
    }
    public async postHelloWorldReadonly(params: Params$postHelloWorldReadonly, option?: RequestOption): Promise<Response$postHelloWorldReadonly$Status$200["application/json"]> {
        const url = this.baseUrl + `/hello/world/readonly`;
        const headers = {
            "Content-Type": "application/json",
            Accept: "application/json"
        };
        return this.apiClient.request({
            httpMethod: "POST",
            url,
            headers,
            requestBody: params.requestBody
        }, option);
    }
    public async get$undefined$operation$$id(option?: RequestOption): Promise<Response$get$undefined$operation$$id$Status$200["application/json"]> {
        const url = this.baseUrl + `/undefined/operation/:id`;
        const headers = {
            Accept: "application/json"
        };
        return this.apiClient.request({
            httpMethod: "GET",
            url,
            headers
        }, option);
    }
}
