// 
// Generated by @himenon/openapi-typescript-code-generator v2.0.4
// 
// OpenApi : 3.1.0
// 
// 


export interface Parameter$getItemById {
    id: string;
}
export interface Response$getItemById$Status$200 {
    "application/json": {
        id?: string;
        name?: string;
    };
}
export interface Parameter$getNodeProxyWithPath {
    path: string;
    name: string;
}
export interface Response$getNodeProxyWithPath$Status$200 {
    "application/json": string;
}
export interface Parameter$headNodeProxyWithPath {
    path: string;
    name: string;
}
export interface Parameter$getUserPost {
    include?: string;
    userId: string;
    postId: number;
}
export interface Response$getUserPost$Status$200 {
    "application/json": {
        userId?: string;
        postId?: number;
    };
}
export type ResponseContentType$getItemById = keyof Response$getItemById$Status$200;
export interface Params$getItemById {
    parameter: Parameter$getItemById;
}
export type ResponseContentType$getNodeProxyWithPath = keyof Response$getNodeProxyWithPath$Status$200;
export interface Params$getNodeProxyWithPath {
    parameter: Parameter$getNodeProxyWithPath;
}
export interface Params$headNodeProxyWithPath {
    parameter: Parameter$headNodeProxyWithPath;
}
export type ResponseContentType$getUserPost = keyof Response$getUserPost$Status$200;
export interface Params$getUserPost {
    parameter: Parameter$getUserPost;
}
export type HttpMethod = "GET" | "PUT" | "POST" | "DELETE" | "OPTIONS" | "HEAD" | "PATCH" | "TRACE";
export interface ObjectLike {
    [key: string]: any;
}
export interface QueryParameter {
    value: any;
    style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    explode: boolean;
}
export interface QueryParameters {
    [key: string]: QueryParameter;
}
export type SuccessResponses = Response$getItemById$Status$200 | Response$getNodeProxyWithPath$Status$200 | Response$getUserPost$Status$200;
export namespace ErrorResponse {
    export type getItemById = void;
    export type getNodeProxyWithPath = void;
    export type headNodeProxyWithPath = void;
    export type getUserPost = void;
}
export interface Encoding {
    readonly contentType?: string;
    headers?: Record<string, any>;
    readonly style?: "form" | "spaceDelimited" | "pipeDelimited" | "deepObject";
    readonly explode?: boolean;
    readonly allowReserved?: boolean;
}
export interface RequestArgs {
    readonly httpMethod: HttpMethod;
    readonly url: string;
    headers: ObjectLike | any;
    requestBody?: ObjectLike | any;
    requestBodyEncoding?: Record<string, Encoding>;
    queryParameters?: QueryParameters | undefined;
}
export interface ApiClient<RequestOption> {
    request: <T = SuccessResponses>(requestArgs: RequestArgs, options?: RequestOption) => Promise<T>;
}
export class Client<RequestOption> {
    private baseUrl: string;
    constructor(private apiClient: ApiClient<RequestOption>, baseUrl: string) { this.baseUrl = baseUrl.replace(/\/$/, ""); }
    /** required フィールドを省略したパスパラメータ */
    public async getItemById(params: Params$getItemById, option?: RequestOption): Promise<Response$getItemById$Status$200["application/json"]> {
        const url = this.baseUrl + `/items/${encodeURIComponent(params.parameter.id)}`;
        const headers = {
            Accept: "application/json"
        };
        return this.apiClient.request({
            httpMethod: "GET",
            url,
            headers
        }, option);
    }
    /** PathItem レベルのパスパラメータ継承 (GET) */
    public async getNodeProxyWithPath(params: Params$getNodeProxyWithPath, option?: RequestOption): Promise<Response$getNodeProxyWithPath$Status$200["application/json"]> {
        const url = this.baseUrl + `/nodes/${encodeURIComponent(params.parameter.name)}/proxy/${encodeURIComponent(params.parameter.path)}`;
        const headers = {
            Accept: "application/json"
        };
        const queryParameters: QueryParameters = {
            path: { value: params.parameter.path, explode: false }
        };
        return this.apiClient.request({
            httpMethod: "GET",
            url,
            headers,
            queryParameters: queryParameters
        }, option);
    }
    /** PathItem レベルのパスパラメータ継承 (HEAD) */
    public async headNodeProxyWithPath(params: Params$headNodeProxyWithPath, option?: RequestOption): Promise<void> {
        const url = this.baseUrl + `/nodes/${encodeURIComponent(params.parameter.name)}/proxy/${encodeURIComponent(params.parameter.path)}`;
        const headers = {};
        const queryParameters: QueryParameters = {
            path: { value: params.parameter.path, explode: false }
        };
        return this.apiClient.request({
            httpMethod: "HEAD",
            url,
            headers,
            queryParameters: queryParameters
        }, option);
    }
    /** 複数のパスパラメータで required を省略したケース */
    public async getUserPost(params: Params$getUserPost, option?: RequestOption): Promise<Response$getUserPost$Status$200["application/json"]> {
        const url = this.baseUrl + `/users/${encodeURIComponent(params.parameter.userId)}/posts/${encodeURIComponent(params.parameter.postId)}`;
        const headers = {
            Accept: "application/json"
        };
        const queryParameters: QueryParameters = {
            include: { value: params.parameter.include, explode: false }
        };
        return this.apiClient.request({
            httpMethod: "GET",
            url,
            headers,
            queryParameters: queryParameters
        }, option);
    }
}
