// 
// Generated by @himenon/openapi-typescript-code-generator
// 
// OpenApi : 3.0.1
// 
// License  : MIT
// 


export namespace Schemas {
    export interface Pet {
        pet_type: string;
    }
    export type Dog = Schemas.Pet & {
        bark?: boolean;
        breed?: "Dingo" | "Husky" | "Retriever" | "Shepherd";
    };
    export type Cat = Schemas.Pet & {
        hunts?: boolean;
        age?: number;
    };
}
