name: Release Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          registry-url: https://npm.pkg.github.com
          scope: "@Himenon"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: |
          pnpm build

  release-github-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: main
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          registry-url: https://npm.pkg.github.com
          scope: "@Himenon"
          cache: "pnpm"
      - run: pnpm install
      - run: |
          pnpm build
          pnpm run release:github:registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-npm-registry:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          ref: main
      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: NPM_CONFIG_PROVENANCE=true pnpm run release:npm:registry
