name: Version Up

on:
  push:
    branches: [main]

jobs:
  auto-version-up:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Auto version update
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          yarn install --frozen-lockfile
          yarn lerna:version:up
